name = "mimshach"
pages_build_output_dir = "dist"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "mimshach-db"
database_id = "6097ebc5-635b-436e-9b2b-0f8971b12eba"

[[r2_buckets]]
binding = "STORAGE"
bucket_name = "mimshach-images"

[vars]
ENVIRONMENT = "production"
SHOP_NAME = "Mimshach Household Collection"
ADMIN_WHATSAPP = "254706752174"
